export enum Permission {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  APPROVE = 'APPROVE',
  DELETE = 'DELETE',
  MANAGE_TENANTS = 'MANAGE_TENANTS',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_USERS = 'MANAGE_USERS',
}
